name: xcube-resampling
channels:
  - conda-forge
dependencies:
  # Python
  - python >=3.8
  # Required
  - affine >=2.2
  - dask >=2021.6
  - dask-image >=0.6
  - numba >=0.52
  - numpy >=1.16
  - pyproj >=3.0
  - xarray >=2024.7
  - zarr >=2.11,<3  # until we can ensure zarr 3 compatibility
  # Development Dependencies - Tools
  - black
  - isort
  - mkdocs
  - mkdocs-autorefs
  - mkdocs-material
  - mkdocs-jupyter
  - mkdocstrings
  - mkdocstrings-python
  - pytest
  - pytest-cov
  - ruff
  # Development Dependencies - Demos
  - jupyterlab
  - matplotlib

